/* PAR ORDO customer demo. Replace CONFIG URLs with real Instagram/WhatsApp links. */
const CONFIG={
  instagramUrl:'https://www.instagram.com/',
  whatsappGroupUrl:'https://chat.whatsapp.com/',
  currency:'сом',
  hours:'10:00 — 23:00',
  address:'Бишкек, Торокул Айтматова 677'
};
const products=[
 {id:1,name:'Одноразовые шорты',cat:'Шорты',price:50,stock:120,img:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=80'},
 {id:2,name:'Полотенце',cat:'Полотенца',price:200,stock:80,img:'https://images.unsplash.com/photo-1600369671236-e74521d6f0b7?auto=format&fit=crop&w=900&q=80'},
 {id:3,name:'Мыло',cat:'Мыло',price:70,stock:60,img:'https://images.unsplash.com/photo-1607006344380-b6775a0824fb?auto=format&fit=crop&w=900&q=80'},
 {id:4,name:'Трусы мужские',cat:'Трусы',price:40,stock:150,img:'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80'},
 {id:5,name:'Носки',cat:'Носки',price:60,stock:200,img:'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=900&q=80'},
 {id:6,name:'Веник для пара',cat:'Веник',price:350,stock:25,img:'https://images.unsplash.com/photo-1602874801006-e26a3f4c9c5e?auto=format&fit=crop&w=900&q=80'},
 {id:7,name:'Минеральная вода',cat:'Напитки',price:60,stock:50,img:'https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=900&q=80'},
 {id:8,name:'Энергетический напиток',cat:'Напитки',price:120,stock:40,img:'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?auto=format&fit=crop&w=900&q=80'},
 {id:9,name:'Холодный чай',cat:'Напитки',price:100,stock:35,img:'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80'}
];
const state={view:'home',cat:'Все',search:'',cart:JSON.parse(localStorage.getItem('po_cart')||'[]'),orders:JSON.parse(localStorage.getItem('po_orders')||'[]'),customer:JSON.parse(localStorage.getItem('po_customer')||'{}')};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem('po_cart',JSON.stringify(state.cart));
const money=n=>`${n.toLocaleString('ru-RU')} ${CONFIG.currency}`;
function setView(view){state.view=view; $$('.view').forEach(x=>x.classList.toggle('active',x.id===view)); $$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); if(view==='catalog')renderCatalog(); if(view==='cart')renderCart(); if(view==='checkout')renderCheckout(); if(view==='orders')renderOrders(); if(view==='notifications')renderNotifications(); if(view==='profile')renderProfile(); window.scrollTo({top:0,behavior:'smooth'});}
function cartCount(){return state.cart.reduce((s,x)=>s+x.qty,0)}
function updateBadges(){const n=cartCount(); $('#cartBadge').textContent=n;$('#navBadge').textContent=n;$('#cartBadge').style.display=n?'block':'none';$('#navBadge').style.display=n?'block':'none'}
function cats(){return ['Все','Шорты','Полотенца','Мыло','Трусы','Носки','Веник','Напитки']}
function renderCats(){const bar=$('#categoryBar');bar.innerHTML=cats().map(c=>`<button class="chip ${state.cat===c?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;renderCats();renderCatalog()})}
function visibleProducts(){return products.filter(p=>(state.cat==='Все'||p.cat===state.cat)&&(!state.search||p.name.toLowerCase().includes(state.search.toLowerCase())))}
function renderCatalog(){renderCats();const grid=$('#productGrid');const list=visibleProducts();grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-img"><img loading="lazy" src="${p.img}" alt="${p.name}"></div><div class="body"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><span class="stock">В наличии · ${p.stock} шт.</span><div class="product-actions"><button class="btn btn-small btn-cart" data-add="${p.id}">🛒 В корзину</button><button class="btn btn-small btn-buy" data-buy="${p.id}">Купить</button></div></div></article>`).join('')||`<div class="muted">Товары не найдены.</div>`;$$('[data-add]').forEach(b=>b.onclick=()=>addCart(+b.dataset.add));$$('[data-buy]').forEach(b=>b.onclick=()=>buyNow(+b.dataset.buy))}
function addCart(id,qty=1){const p=products.find(x=>x.id===id);const item=state.cart.find(x=>x.id===id);if(item)item.qty=Math.min(p.stock,item.qty+qty);else state.cart.push({id,qty:Math.min(p.stock,qty)});save();updateBadges();toast(`${p.name} добавлен в корзину`)}
function buyNow(id){addCart(id);setView('checkout')}
function total(){return state.cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0)}
function renderProduct(id){const p=products.find(x=>x.id===id);$('#product').innerHTML=`<div class="detail-card"><div class="detail-img"><img src="${p.img}" alt="${p.name}"></div><div class="detail-body"><span class="eyebrow">${p.cat}</span><h2>${p.name}</h2><div class="price">${money(p.price)}</div><div class="detail-row"><span class="stock">В наличии · ${p.stock} шт.</span><div class="qty"><button id="dqMinus">−</button><b id="dq">1</b><button id="dqPlus">+</button></div></div><div class="product-actions"><button class="btn btn-cart" id="detailCart">В корзину</button><button class="btn btn-buy" id="detailBuy">Купить сейчас</button></div><div style="margin-top:16px;line-height:1.55;font-size:13px;color:#d9cab8">✅ Подходит для бани и отдыха<br>✅ Удобно и быстро<br>✅ Качество и чистота</div><button class="btn" style="margin-top:16px;background:#261a10;border:1px solid #4a311b" data-view="catalog">← Назад в каталог</button></div></div>`;let q=1;$('#dqMinus').onclick=()=>{q=Math.max(1,q-1);$('#dq').textContent=q};$('#dqPlus').onclick=()=>{q=Math.min(p.stock,q+1);$('#dq').textContent=q};$('#detailCart').onclick=()=>addCart(id,q);$('#detailBuy').onclick=()=>{addCart(id,q);setView('checkout')};$$('[data-view="catalog"]').forEach(b=>b.onclick=()=>setView('catalog'));}
function renderCart(){const el=$('#cart');if(!state.cart.length){el.innerHTML=`<div class="cart-card" style="padding:30px;text-align:center"><div style="font-size:50px">🛒</div><h2>Корзина пуста</h2><p class="muted">Добавьте товары для заказа.</p><button class="btn btn-gold" data-view="catalog">Перейти в каталог</button></div>`;bindViewButtons();return}const rows=state.cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="cart-row"><img src="${p.img}" alt="${p.name}"><div><h3>${p.name}</h3><small>${money(p.price)} · ${x.qty} шт.</small><div style="margin-top:7px" class="qty"><button data-dec="${p.id}">−</button><b>${x.qty}</b><button data-inc="${p.id}">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');el.innerHTML=`<div class="cart-card"><div style="padding:16px"><span class="eyebrow">ПАР ОРДО</span><h2 style="margin:0">Корзина (${cartCount()})</h2></div>${rows}<div class="total-row"><span>Итого</span><b>${money(total())}</b></div><div style="padding:0 14px 16px;display:grid;gap:8px"><button class="btn btn-gold" data-view="checkout">Оформить заказ →</button><button class="btn" style="background:#21150d;border:1px solid #4e321a" data-view="catalog">Продолжить покупки</button></div></div>`;$$('[data-dec]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.dec,-1));$$('[data-inc]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.inc,1));bindViewButtons()}
function changeQty(id,d){const item=state.cart.find(x=>x.id===id);const p=products.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);else item.qty=Math.min(p.stock,item.qty);save();updateBadges();renderCart()}
function renderCheckout(){const el=$('#checkout');if(!state.cart.length){setView('cart');return}el.innerHTML=`<div class="checkout-card" style="padding:16px"><span class="eyebrow">ШАГ 1 / 2</span><h2 style="margin:0 0 12px">Оформление заказа</h2><div style="display:grid;gap:8px"><input id="name" placeholder="Ваше имя" value="${state.customer.name||''}" style="padding:13px;border-radius:12px;border:1px solid #4b331d;background:#fff;color:#111"><input id="phone" placeholder="Номер телефона" value="${state.customer.phone||''}" style="padding:13px;border-radius:12px;border:1px solid #4b331d;background:#fff;color:#111"><div class="status">📍 Получение товара: <b>в ПАР ОРДО</b><br><span class="muted">Доставки нет.</span></div><div class="total-row" style="padding:10px 0"><span>К оплате</span><b>${money(total())}</b></div><div class="payment-grid"><button class="pay-btn" id="qrPay">▣<br>QR ОПЛАТА<br><small>Быстро и удобно</small></button><button class="pay-btn cash" id="cashPay">▤<br>НАЛИЧНЫМИ<br><small>Оплата администратору</small></button></div></div></div>`;$('#qrPay').onclick=()=>createOrder('QR');$('#cashPay').onclick=()=>createOrder('Наличные')}
function createOrder(method){const name=$('#name').value.trim();const phone=$('#phone').value.trim();if(!name||!phone)return toast('Укажите имя и телефон');state.customer={name,phone};localStorage.setItem('po_customer',JSON.stringify(state.customer));const order={id:1025+state.orders.length,total:total(),method,status:'Ожидает оплаты',createdAt:new Date().toISOString(),items:state.cart.map(x=>({...x}))};if(method==='QR')openQr(order);else openCash(order);}
function openQr(order){$('#modalCard').innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">Оплата через QR</h2><button class="icon-btn" id="closeModal">×</button></div><p>Заказ №${order.id} · К оплате <b>${money(order.total)}</b></p><div class="qr-box"><canvas id="qrCanvas" width="320" height="320"></canvas><b>Сумма: ${money(order.total)}</b></div><div class="status" style="margin-top:10px">После успешной оплаты статус можно подтвердить автоматически через платёжный backend.</div><button class="btn btn-gold" style="margin-top:10px" id="markDemoPaid">Я оплатил · проверить</button>`;openModal();fakeQr('PARORDO|ORDER:'+order.id+'|SUM:'+order.total);$('#markDemoPaid').onclick=()=>finalizeOrder(order,'Оплачено')}
function openCash(order){$('#modalCard').innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">Оплата наличными</h2><button class="icon-btn" id="closeModal">×</button></div><div class="success" style="padding:20px 0"><div style="font-size:58px">💵</div><h3>К оплате: ${money(order.total)}</h3><p class="muted">Покажите эту сумму администратору и оплатите наличными.</p><button class="btn btn-gold" id="cashPaid">Я оплатил наличными</button><div class="status" style="margin-top:10px">Статус изменит только администратор после подтверждения оплаты.</div></div>`;openModal();$('#cashPaid').onclick=()=>finalizeOrder(order,'Оплата ожидается')}
function finalizeOrder(order,status){order.status=status;state.orders.unshift(order);localStorage.setItem('po_orders',JSON.stringify(state.orders));state.cart=[];save();updateBadges();closeModal();renderSuccess(order)}
function renderSuccess(order){$('#checkout').innerHTML=`<div class="success cart-card"><div class="mark">✓</div><h2>Заказ оформлен!</h2><p>Заказ №${order.id}</p><h3>${money(order.total)}</h3><p>Способ оплаты: ${order.method}</p><span class="badge ${order.status==='Оплачено'?'ok':'wait'}">${order.status}</span><p class="muted">Спасибо! Ждём вас в ПАР ОРДО 🔥</p><button class="btn btn-gold" data-view="home">Вернуться на главную</button><button class="btn" style="margin-top:8px;background:#21150d;border:1px solid #4e321a" data-view="orders">Мои заказы</button></div>`;bindViewButtons()}
function renderOrders(){const el=$('#orders');const arr=state.orders;el.innerHTML=`<div class="list-card"><div style="padding:16px"><span class="eyebrow">ПАР ОРДО</span><h2 style="margin:0">Мои заказы</h2></div>${arr.length?arr.map(o=>`<div class="order-item"><div><b>№${o.id}</b><div class="muted" style="font-size:10px">${new Date(o.createdAt).toLocaleString('ru-RU')} · ${o.method}</div></div><div style="text-align:right"><b>${money(o.total)}</b><div><span class="badge ${o.status==='Оплачено'?'ok':'wait'}">${o.status}</span></div></div></div>`).join(''):`<div style="padding:20px;color:#bcae9c">Пока заказов нет.</div>`}</div>`}
function renderNotifications(){const items=[['Добрый день!','Сегодня свежий веник для пара 🌿'],['Акция!','Полотенца по специальной цене 🔥'],['Новое поступление','Одноразовые шорты снова в наличии'],['Вечерний отдых','Ждём вас в ПАР ОРДО — 10:00–23:00']];$('#notifications').innerHTML=`<div class="list-card"><div style="padding:16px"><span class="eyebrow">PUSH</span><h2 style="margin:0">Уведомления</h2><p class="muted" style="font-size:11px">Только после согласия пользователя.</p></div>${items.map((x,i)=>`<div class="notification"><img src="./assets/par-ordo-logo.jpg"><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('')}<div style="padding:16px"><button class="btn btn-gold" id="enablePush">🔔 Разрешить уведомления</button></div></div>`;$('#enablePush').onclick=subscribePush}
function renderProfile(){const c=state.customer;$('#profile').innerHTML=`<div class="profile-card"><img src="./assets/par-ordo-logo.jpg"><h2>${c.name||'Гость'}</h2><p class="muted">${c.phone||'Добавьте номер при первом заказе'}</p><div class="profile-menu"><button data-view="orders">▤ Мои заказы</button><button data-view="notifications">🔔 Уведомления</button><button id="socialIg">◎ Instagram</button><button id="socialWa">◉ WhatsApp группа</button><button id="showInfo">ℹ О бане</button></div></div>`;bindViewButtons();$('#socialIg').onclick=()=>window.open(CONFIG.instagramUrl,'_blank','noopener');$('#socialWa').onclick=()=>window.open(CONFIG.whatsappGroupUrl,'_blank','noopener');$('#showInfo').onclick=()=>toast(`${CONFIG.hours} · ${CONFIG.address}`)}
function bindViewButtons(){$$('[data-view]').forEach(b=>b.onclick=e=>{e.preventDefault();setView(b.dataset.view);$('#drawer').classList.remove('open')})}
function openModal(){ $('#modal').classList.add('open');$('#closeModal').onclick=closeModal }
function closeModal(){$('#modal').classList.remove('open')}
function fakeQr(text){const c=$('#qrCanvas');const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,320,320);ctx.fillStyle='#111';let seed=[...text].reduce((a,ch)=>((a*31+ch.charCodeAt(0))>>>0),1);for(let y=0;y<29;y++)for(let x=0;x<29;x++){seed=(seed*1664525+1013904223)>>>0;if(seed%3===0)ctx.fillRect(20+x*10,20+y*10,10,10)}[['0','0'],['22','0'],['0','22']].forEach(([xx,yy])=>{ctx.fillStyle='#fff';ctx.fillRect(20+xx*10,20+yy*10,70,70);ctx.fillStyle='#111';ctx.fillRect(30+xx*10,30+yy*10,50,50);ctx.fillStyle='#fff';ctx.fillRect(40+xx*10,40+yy*10,30,30)})}
function toast(msg){const t=document.createElement('div');t.textContent=msg;t.style='position:fixed;left:50%;bottom:84px;transform:translateX(-50%);z-index:999;background:#18100a;border:1px solid #765022;color:#ffe4a1;padding:12px 15px;border-radius:14px;box-shadow:0 10px 30px #000';document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
async function subscribePush(){if(!('Notification'in window)){toast('Браузер не поддерживает уведомления');return}const p=await Notification.requestPermission();toast(p==='granted'?'Уведомления разрешены ✅':'Уведомления отключены')}
$('#menuBtn').onclick=()=>$('#drawer').classList.add('open');$('#drawerClose').onclick=()=>$('#drawer').classList.remove('open');$('#searchBtn').onclick=()=>{$('#searchRow').classList.toggle('hidden');$('#searchInput').focus()};$('#searchClose').onclick=()=>{$('#searchRow').classList.add('hidden');state.search='';renderCatalog()};$('#searchInput').oninput=e=>{state.search=e.target.value;renderCatalog()};document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){e.preventDefault();if(v.closest('#product'))return;setView(v.dataset.view)}});document.addEventListener('click',e=>{const p=e.target.closest('.product-card');if(p&&!e.target.closest('button')){const img=p.querySelector('img');const id=products.find(x=>x.name===p.querySelector('h3').textContent)?.id;if(id){setView('product');renderProduct(id)}}});$$('[data-external]').forEach(a=>a.onclick=e=>{e.preventDefault();window.open(a.dataset.external==='instagram'?CONFIG.instagramUrl:CONFIG.whatsappGroupUrl,'_blank','noopener')});updateBadges();setView('home');
